CREATE TABLE CovidData (
    iso_code VARCHAR(10),
    continent VARCHAR(50),
    location VARCHAR(100),
    date DATE,
    total_cases BIGINT,
    new_cases BIGINT,
    new_cases_smoothed DECIMAL(10, 3),
    total_deaths BIGINT,
    new_deaths BIGINT,
    new_deaths_smoothed DECIMAL(10, 3),
    total_cases_per_million DECIMAL(10, 3),
    new_cases_per_million DECIMAL(10, 3),
    new_cases_smoothed_per_million DECIMAL(10, 3),
    total_deaths_per_million DECIMAL(10, 3),
    new_deaths_per_million DECIMAL(10, 3),
    new_deaths_smoothed_per_million DECIMAL(10, 3),
    reproduction_rate DECIMAL(10, 2),
    icu_patients BIGINT,
    icu_patients_per_million DECIMAL(10, 3),
    hosp_patients BIGINT,
    hosp_patients_per_million DECIMAL(10, 3),
    weekly_icu_admissions BIGINT,
    weekly_icu_admissions_per_million DECIMAL(10, 3),
    weekly_hosp_admissions BIGINT,
    weekly_hosp_admissions_per_million DECIMAL(10, 3),
    new_tests BIGINT,
    total_tests BIGINT,
    total_tests_per_thousand DECIMAL(10, 3),
    new_tests_per_thousand DECIMAL(10, 3),
    new_tests_smoothed BIGINT,
    new_tests_smoothed_per_thousand DECIMAL(10, 3),
    positive_rate DECIMAL(10, 3),
    tests_per_case DECIMAL(10, 3),
    tests_units VARCHAR(100),
    total_vaccinations BIGINT,
    people_vaccinated BIGINT,
    people_fully_vaccinated BIGINT,
    new_vaccinations BIGINT,
    new_vaccinations_smoothed BIGINT,
    total_vaccinations_per_hundred DECIMAL(10, 3),
    people_vaccinated_per_hundred DECIMAL(10, 3),
    people_fully_vaccinated_per_hundred DECIMAL(10, 3),
    new_vaccinations_smoothed_per_million DECIMAL(10, 3),
    stringency_index DECIMAL(10, 3),
    population BIGINT,
    population_density DECIMAL(10, 3),
    median_age DECIMAL(10, 3),
    aged_65_older DECIMAL(10, 3),
    aged_70_older DECIMAL(10, 3),
    gdp_per_capita DECIMAL(10, 3),
    extreme_poverty DECIMAL(10, 1),
    cardiovasc_death_rate DECIMAL(10, 3),
    diabetes_prevalence DECIMAL(10, 2),
    female_smokers DECIMAL(10, 1),
    male_smokers DECIMAL(10, 1),
    handwashing_facilities DECIMAL(10, 3),
    hospital_beds_per_thousand DECIMAL(10,3),
    life_expectancy DECIMAL(10, 3),
    human_development_index DECIMAL(10, 3)
);






CREATE TABLE CovidVaccinations (
    iso_code VARCHAR(10),
    continent VARCHAR(50),
    location VARCHAR(100),
    date DATE,
    new_tests BIGINT,
    total_tests BIGINT,
    total_tests_per_thousand DECIMAL(10, 3),
    new_tests_per_thousand DECIMAL(10, 3),
    new_tests_smoothed BIGINT,
    new_tests_smoothed_per_thousand DECIMAL(10, 3),
    positive_rate DECIMAL(10, 3),
    tests_per_case DECIMAL(10, 1),
    tests_units VARCHAR(100),
    total_vaccinations BIGINT,
    people_vaccinated BIGINT,
    people_fully_vaccinated BIGINT,
    new_vaccinations BIGINT,
    new_vaccinations_smoothed BIGINT,
    total_vaccinations_per_hundred DECIMAL(10, 2),
    people_vaccinated_per_hundred DECIMAL(10, 2),
    people_fully_vaccinated_per_hundred DECIMAL(10, 2),
    new_vaccinations_smoothed_per_million BIGINT,
    stringency_index DECIMAL(10, 2),
    population_density DECIMAL(10, 3),
    median_age DECIMAL(10, 1),
    aged_65_older DECIMAL(10, 3),
    aged_70_older DECIMAL(10, 3),
    gdp_per_capita DECIMAL(10, 3),
    extreme_poverty DECIMAL(10, 1),
    cardiovasc_death_rate DECIMAL(10, 3),
    diabetes_prevalence DECIMAL(10, 2),
    female_smokers DECIMAL(10, 1),
    male_smokers DECIMAL(10, 1),
    handwashing_facilities DECIMAL(10, 3),
    hospital_beds_per_thousand DECIMAL(10, 1),
    life_expectancy DECIMAL(10, 2),
    human_development_index DECIMAL(10, 3)
);